# ===========================
# Variables
# ===========================

$mod = SUPER
$terminal = kitty
$menu = rofi -show drun

# ===========================
# Load configuration
# ===========================

source = ~/.config/hypr/environment.conf
source = ~/.config/hypr/monitor.conf
source = ~/.config/hypr/input.conf
source = ~/.config/hypr/appearance.conf
source = ~/.config/hypr/animations.conf
source = ~/.config/hypr/windowrules.conf
source = ~/.config/hypr/keybinds.conf
source = ~/.config/hypr/autostart.conf

preload = /home/bow/Downloads/chainsaw-man-the-5120x2880-22996.jpg
wallpaper = ,/home/bow/Downloads/chainsaw-man-the-5120x2880-22996.jpg